import { FunctionComponent } from "react";
import Field40defaultdropdown from "./field40defaultdropdown";
import styles from "./profile-form.module.css";

type ProfileFormType = {
  viewFillIcon?: boolean;
  viewFillIcon1?: boolean;
  viewFillIcon2?: boolean;
  viewFillIcon3?: boolean;
  viewFillIcon4?: boolean;
  viewFillIcon5?: boolean;
  viewFillIcon6?: boolean;
  viewFillIcon7?: boolean;
  viewFillIcon8?: boolean;
  viewFillIcon9?: boolean;
  viewFillIcon10?: boolean;
  viewFillIcon11?: boolean;
  viewFillIcon12?: boolean;
};

const ProfileForm: FunctionComponent<ProfileFormType> = ({
  viewFillIcon,
  viewFillIcon1,
  viewFillIcon2,
  viewFillIcon3,
  viewFillIcon4,
  viewFillIcon5,
  viewFillIcon6,
  viewFillIcon7,
  viewFillIcon8,
  viewFillIcon9,
  viewFillIcon10,
  viewFillIcon11,
  viewFillIcon12,
}) => {
  return (
    <div className={styles.field40defaultdropdownParent}>
      <Field40defaultdropdown
        email="Input your BIO"
        showViewFillIcon={false}
        field40defaultdropdownPosition="relative"
        field40defaultdropdownWidth="24.75rem"
        field40defaultdropdownTop="unset"
        field40defaultdropdownRight="unset"
        field40defaultdropdownLeft="unset"
        field40defaultdropdownHeight="4.38rem"
        field40defaultdropdownBottom="unset"
        rectangleDivBackgroundColor="unset"
        rectangleDivBorder="1px solid var(--grey-20)"
        rectangleDivTop="0rem"
        rectangleDivRight="0rem"
        rectangleDivBottom="0rem"
        rectangleDivLeft="0rem"
        emailColor="#ccd2e3"
        emailLeft="0.75rem"
        emailLineHeight="1rem"
        emailTop="calc(50% - 8px)"
        emailFontSize="12px"
        emailDisplay="inline-block"
        emailAlignItems="unset"
        emailWidth="unset"
        viewFillIconTop="0.5rem"
        viewFillIconRight="0.75rem"
        viewFillIconWidth="1.5rem"
        viewFillIconHeight="1.5rem"
        viewFillIconPosition="absolute"
        viewFillIconLineBreak="unset"
      />
      <div className={styles.photogrammetry}>
        <div className={styles.uploadProfileImage}>Upload Profile Image</div>
        <img className={styles.icon} alt="" src="/icon5.svg" />
      </div>
      <Field40defaultdropdown
        email="Personal Site"
        showViewFillIcon={false}
        field40defaultdropdownPosition="relative"
        field40defaultdropdownWidth="24.75rem"
        field40defaultdropdownTop="unset"
        field40defaultdropdownRight="unset"
        field40defaultdropdownLeft="unset"
        field40defaultdropdownHeight="2.5rem"
        field40defaultdropdownBottom="unset"
        rectangleDivBackgroundColor="unset"
        rectangleDivBorder="1px solid var(--grey-20)"
        rectangleDivTop="0rem"
        rectangleDivRight="0rem"
        rectangleDivBottom="0rem"
        rectangleDivLeft="0rem"
        emailColor="#ccd2e3"
        emailLeft="0.75rem"
        emailLineHeight="1.5rem"
        emailTop="calc(50% - 12px)"
        emailFontSize="12px"
        emailDisplay="inline-block"
        emailAlignItems="unset"
        emailWidth="calc(100% - 24px)"
        viewFillIconTop="0.5rem"
        viewFillIconRight="0.75rem"
        viewFillIconWidth="1.5rem"
        viewFillIconHeight="1.5rem"
        viewFillIconPosition="absolute"
        viewFillIconLineBreak="unset"
      />
      <Field40defaultdropdown
        email="University Email"
        showViewFillIcon={false}
        field40defaultdropdownPosition="relative"
        field40defaultdropdownWidth="24.75rem"
        field40defaultdropdownTop="unset"
        field40defaultdropdownRight="unset"
        field40defaultdropdownLeft="unset"
        field40defaultdropdownHeight="2.5rem"
        field40defaultdropdownBottom="unset"
        rectangleDivBackgroundColor="unset"
        rectangleDivBorder="1px solid var(--grey-20)"
        rectangleDivTop="0rem"
        rectangleDivRight="0rem"
        rectangleDivBottom="0rem"
        rectangleDivLeft="0rem"
        emailColor="#ccd2e3"
        emailLeft="0.75rem"
        emailLineHeight="1.5rem"
        emailTop="calc(50% - 12px)"
        emailFontSize="12px"
        emailDisplay="inline-block"
        emailAlignItems="unset"
        emailWidth="calc(100% - 24px)"
        viewFillIconTop="0.5rem"
        viewFillIconRight="0.75rem"
        viewFillIconWidth="1.5rem"
        viewFillIconHeight="1.5rem"
        viewFillIconPosition="absolute"
        viewFillIconLineBreak="unset"
      />
      <Field40defaultdropdown
        field40defaultdropdownPosition="relative"
        field40defaultdropdownWidth="24.75rem"
        field40defaultdropdownTop="unset"
        field40defaultdropdownRight="unset"
        field40defaultdropdownLeft="unset"
        field40defaultdropdownHeight="2.5rem"
        field40defaultdropdownBottom="unset"
        rectangleDivBackgroundColor="unset"
        rectangleDivBorder="1px solid var(--grey-20)"
        rectangleDivTop="0rem"
        rectangleDivRight="0rem"
        rectangleDivBottom="0rem"
        rectangleDivLeft="0rem"
        emailColor="#ccd2e3"
        emailLeft="0.75rem"
        emailLineHeight="unset"
        emailTop="calc(50% - 15px)"
        emailFontSize="unset"
        emailDisplay="flex"
        emailAlignItems="center"
        emailWidth="calc(100% - 24px)"
      />
      <Field40defaultdropdown
        email="DOI "
        showViewFillIcon={false}
        field40defaultdropdownPosition="relative"
        field40defaultdropdownWidth="24.75rem"
        field40defaultdropdownTop="unset"
        field40defaultdropdownRight="unset"
        field40defaultdropdownLeft="unset"
        field40defaultdropdownHeight="2.5rem"
        field40defaultdropdownBottom="unset"
        rectangleDivBackgroundColor="unset"
        rectangleDivBorder="1px solid var(--grey-20)"
        rectangleDivTop="0rem"
        rectangleDivRight="0rem"
        rectangleDivBottom="0rem"
        rectangleDivLeft="0rem"
        emailColor="#ccd2e3"
        emailLeft="0.75rem"
        emailLineHeight="1.5rem"
        emailTop="calc(50% - 12px)"
        emailFontSize="12px"
        emailDisplay="inline-block"
        emailAlignItems="unset"
        emailWidth="calc(100% - 24px)"
        viewFillIconTop="0.5rem"
        viewFillIconRight="0.75rem"
        viewFillIconWidth="1.5rem"
        viewFillIconHeight="1.5rem"
        viewFillIconPosition="absolute"
        viewFillIconLineBreak="unset"
      />
      <Field40defaultdropdown
        email="Profession"
        showViewFillIcon={false}
        field40defaultdropdownPosition="relative"
        field40defaultdropdownWidth="24.75rem"
        field40defaultdropdownTop="unset"
        field40defaultdropdownRight="unset"
        field40defaultdropdownLeft="unset"
        field40defaultdropdownHeight="2.5rem"
        field40defaultdropdownBottom="unset"
        rectangleDivBackgroundColor="unset"
        rectangleDivBorder="1px solid var(--grey-20)"
        rectangleDivTop="0rem"
        rectangleDivRight="0rem"
        rectangleDivBottom="0rem"
        rectangleDivLeft="0rem"
        emailColor="#ccd2e3"
        emailLeft="0.75rem"
        emailLineHeight="1.5rem"
        emailTop="calc(50% - 12px)"
        emailFontSize="12px"
        emailDisplay="inline-block"
        emailAlignItems="unset"
        emailWidth="calc(100% - 24px)"
        viewFillIconTop="0.5rem"
        viewFillIconRight="0.75rem"
        viewFillIconWidth="1.5rem"
        viewFillIconHeight="1.5rem"
        viewFillIconPosition="absolute"
        viewFillIconLineBreak="unset"
      />
      <Field40defaultdropdown
        email="LinkedIn URL"
        showViewFillIcon={false}
        field40defaultdropdownPosition="relative"
        field40defaultdropdownWidth="24.75rem"
        field40defaultdropdownTop="unset"
        field40defaultdropdownRight="unset"
        field40defaultdropdownLeft="unset"
        field40defaultdropdownHeight="2.5rem"
        field40defaultdropdownBottom="unset"
        rectangleDivBackgroundColor="unset"
        rectangleDivBorder="1px solid var(--grey-20)"
        rectangleDivTop="0rem"
        rectangleDivRight="0rem"
        rectangleDivBottom="0rem"
        rectangleDivLeft="0rem"
        emailColor="#ccd2e3"
        emailLeft="0.75rem"
        emailLineHeight="1.5rem"
        emailTop="calc(50% - 12px)"
        emailFontSize="12px"
        emailDisplay="inline-block"
        emailAlignItems="unset"
        emailWidth="calc(100% - 24px)"
        viewFillIconTop="0.5rem"
        viewFillIconRight="0.75rem"
        viewFillIconWidth="1.5rem"
        viewFillIconHeight="1.5rem"
        viewFillIconPosition="absolute"
        viewFillIconLineBreak="unset"
      />
      <Field40defaultdropdown
        email=" OrcID"
        showViewFillIcon={false}
        field40defaultdropdownPosition="relative"
        field40defaultdropdownWidth="24.75rem"
        field40defaultdropdownTop="unset"
        field40defaultdropdownRight="unset"
        field40defaultdropdownLeft="unset"
        field40defaultdropdownHeight="2.5rem"
        field40defaultdropdownBottom="unset"
        rectangleDivBackgroundColor="unset"
        rectangleDivBorder="1px solid var(--grey-20)"
        rectangleDivTop="0rem"
        rectangleDivRight="0rem"
        rectangleDivBottom="0rem"
        rectangleDivLeft="0rem"
        emailColor="#ccd2e3"
        emailLeft="0.75rem"
        emailLineHeight="1.5rem"
        emailTop="calc(50% - 12px)"
        emailFontSize="12px"
        emailDisplay="inline-block"
        emailAlignItems="unset"
        emailWidth="calc(100% - 24px)"
        viewFillIconTop="0.5rem"
        viewFillIconRight="0.75rem"
        viewFillIconWidth="1.5rem"
        viewFillIconHeight="1.5rem"
        viewFillIconPosition="absolute"
        viewFillIconLineBreak="unset"
      />
      <Field40defaultdropdown
        email="Twitter URL"
        showViewFillIcon={false}
        field40defaultdropdownPosition="relative"
        field40defaultdropdownWidth="24.75rem"
        field40defaultdropdownTop="unset"
        field40defaultdropdownRight="unset"
        field40defaultdropdownLeft="unset"
        field40defaultdropdownHeight="2.5rem"
        field40defaultdropdownBottom="unset"
        rectangleDivBackgroundColor="unset"
        rectangleDivBorder="1px solid var(--grey-20)"
        rectangleDivTop="0rem"
        rectangleDivRight="0rem"
        rectangleDivBottom="0rem"
        rectangleDivLeft="0rem"
        emailColor="#ccd2e3"
        emailLeft="0.75rem"
        emailLineHeight="1.5rem"
        emailTop="calc(50% - 12px)"
        emailFontSize="12px"
        emailDisplay="inline-block"
        emailAlignItems="unset"
        emailWidth="calc(100% - 24px)"
        viewFillIconTop="0.5rem"
        viewFillIconRight="0.75rem"
        viewFillIconWidth="1.5rem"
        viewFillIconHeight="1.5rem"
        viewFillIconPosition="absolute"
        viewFillIconLineBreak="unset"
      />
      <Field40defaultdropdown
        email="Mastodon URL"
        showViewFillIcon={false}
        field40defaultdropdownPosition="relative"
        field40defaultdropdownWidth="24.75rem"
        field40defaultdropdownTop="unset"
        field40defaultdropdownRight="unset"
        field40defaultdropdownLeft="unset"
        field40defaultdropdownHeight="2.5rem"
        field40defaultdropdownBottom="unset"
        rectangleDivBackgroundColor="unset"
        rectangleDivBorder="1px solid var(--grey-20)"
        rectangleDivTop="0rem"
        rectangleDivRight="0rem"
        rectangleDivBottom="0rem"
        rectangleDivLeft="0rem"
        emailColor="#ccd2e3"
        emailLeft="0.75rem"
        emailLineHeight="1.5rem"
        emailTop="calc(50% - 12px)"
        emailFontSize="12px"
        emailDisplay="inline-block"
        emailAlignItems="unset"
        emailWidth="calc(100% - 24px)"
        viewFillIconTop="0.5rem"
        viewFillIconRight="0.75rem"
        viewFillIconWidth="1.5rem"
        viewFillIconHeight="1.5rem"
        viewFillIconPosition="absolute"
        viewFillIconLineBreak="unset"
      />
      <Field40defaultdropdown
        email="GitHub"
        showViewFillIcon={false}
        field40defaultdropdownPosition="relative"
        field40defaultdropdownWidth="24.75rem"
        field40defaultdropdownTop="unset"
        field40defaultdropdownRight="unset"
        field40defaultdropdownLeft="unset"
        field40defaultdropdownHeight="2.5rem"
        field40defaultdropdownBottom="unset"
        rectangleDivBackgroundColor="unset"
        rectangleDivBorder="1px solid var(--grey-20)"
        rectangleDivTop="0rem"
        rectangleDivRight="0rem"
        rectangleDivBottom="0rem"
        rectangleDivLeft="0rem"
        emailColor="#ccd2e3"
        emailLeft="0.75rem"
        emailLineHeight="1.5rem"
        emailTop="calc(50% - 12px)"
        emailFontSize="12px"
        emailDisplay="inline-block"
        emailAlignItems="unset"
        emailWidth="calc(100% - 24px)"
        viewFillIconTop="0.5rem"
        viewFillIconRight="0.75rem"
        viewFillIconWidth="1.5rem"
        viewFillIconHeight="1.5rem"
        viewFillIconPosition="absolute"
        viewFillIconLineBreak="unset"
      />
      <Field40defaultdropdown
        email="GitLab"
        showViewFillIcon={false}
        field40defaultdropdownPosition="relative"
        field40defaultdropdownWidth="24.75rem"
        field40defaultdropdownTop="unset"
        field40defaultdropdownRight="unset"
        field40defaultdropdownLeft="unset"
        field40defaultdropdownHeight="2.5rem"
        field40defaultdropdownBottom="unset"
        rectangleDivBackgroundColor="unset"
        rectangleDivBorder="1px solid var(--grey-20)"
        rectangleDivTop="0rem"
        rectangleDivRight="0rem"
        rectangleDivBottom="0rem"
        rectangleDivLeft="0rem"
        emailColor="#ccd2e3"
        emailLeft="0.75rem"
        emailLineHeight="1.5rem"
        emailTop="calc(50% - 12px)"
        emailFontSize="12px"
        emailDisplay="inline-block"
        emailAlignItems="unset"
        emailWidth="calc(100% - 24px)"
        viewFillIconTop="0.5rem"
        viewFillIconRight="0.75rem"
        viewFillIconWidth="1.5rem"
        viewFillIconHeight="1.5rem"
        viewFillIconPosition="absolute"
        viewFillIconLineBreak="unset"
      />
      <Field40defaultdropdown
        email="Enter instagram handle"
        showViewFillIcon={false}
        field40defaultdropdownPosition="relative"
        field40defaultdropdownWidth="24.75rem"
        field40defaultdropdownTop="unset"
        field40defaultdropdownRight="unset"
        field40defaultdropdownLeft="unset"
        field40defaultdropdownHeight="2.5rem"
        field40defaultdropdownBottom="unset"
        rectangleDivBackgroundColor="unset"
        rectangleDivBorder="1px solid var(--grey-20)"
        rectangleDivTop="0rem"
        rectangleDivRight="0rem"
        rectangleDivBottom="0rem"
        rectangleDivLeft="0rem"
        emailColor="#ccd2e3"
        emailLeft="0.75rem"
        emailLineHeight="1.5rem"
        emailTop="calc(50% - 12px)"
        emailFontSize="12px"
        emailDisplay="inline-block"
        emailAlignItems="unset"
        emailWidth="calc(100% - 24px)"
        viewFillIconTop="0.5rem"
        viewFillIconRight="0.75rem"
        viewFillIconWidth="1.5rem"
        viewFillIconHeight="1.5rem"
        viewFillIconPosition="absolute"
        viewFillIconLineBreak="unset"
      />
    </div>
  );
};

export default ProfileForm;
